In [1]:
import keras.backend as K

In [2]:
import keras

In [3]:
import tensorflow as tf

In [4]:
tf.constant(2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
tf.constant([2,3])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [6]:
tf.constant([[2,3],[3,3]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 3]], dtype=int32)>

In [7]:
tf.Variable([[2,3],[3,3]])

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [3, 3]], dtype=int32)>